dataset_pattern: /mnt/hadoop/cms/store/user/bmaier/grapple/ttbar/v4/TTBar_*npz 
output: XXX/64_final_nopuppi_75/ 
n_epochs: 301

embedding_size: 64
hidden_size: 64
intermediate_size: 64
feature_size: 11
num_hidden_layers: 3
num_attention_heads: 4
num_encoders: 4
label_size: 1
attention_band: 75

batch_size: 128 
grad_acc: 8
mask_charged: False
lr: 0.001
lr_decay: 0.97
lr_policy: 'cyclic'
num_max_files: 3
num_max_particles: 9000
plot: XXX/64_final_nopuppi_75/
pt_weight: True
